### ISSUE TITLE
Streams not working 

### ISSUE THREAD

**Issue by ezyfst** [Chris230291/STB-Proxy#15]
I have a question. My portal don't work. It makes connection I can see the playlist, epg but the streams don't work, can you help me?

**Comment by sam5558** [comment]
Hello,
sorry to reopen that issue but i'm having the same issue with built url in playlist, it is showing localhost instead of the actual IP.

I've used in the docker the -e HOST=192.168.240.x:8084, i can access the application through this IP.
But when i generate the playlist i can something like : 
```
#EXTM3U 
#EXTINF:-1 tvg-id="xxxxxxxxxxxxxxxxxxxxxxx" tvg-chno="7287" group-title="xxxxxx",|xx|  xxxx
http://localhost/play/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxx
```
Is it me doing something wrong or is it some bug with the app itself ?

Thank you for your help

**Comment by Chris230291** [comment]
You should make sure the variable is being set correctly when you create the container.
If you run `docker exec <container name> env` it will list all environment variables for that container.

**Comment by sam5558** [comment]
Yes i had probably a misconfiguration on that part.
I'm using unRAID which is using a specific xml format for docker generation, i guess something was done wrong.
I did switch to the classical installation and i confirm it works now.
Thanks
