### ISSUE TITLE
is it possible to get the VOD m3u?

### ISSUE THREAD

**Issue by ezyfst** [Chris230291/STB-Proxy#18]
Is it possible to get the vod part of the stalker portal in m3u?

**Comment by Chris230291** [comment]
Yes and no. Unless somebody knows the URL to get all vods in one request I would have to get each "page" individually, which is about 14 vods at a time. Since a lot of servers have 500 pages or sometimes many more, that is a lot of requests to make which takes minutes to complete. If I run them all in parallel I found some providers would ban me.

Without knowing all of the different portal requests (I only know the ones other apps use by looking at wireshark), its difficult to know what the options are.

I can rework things like the webui so that each page, search etc is a separate request, but remember I am not a programmer and it looked way more complicated. I'd rather keep it as simple as possible. Besides that would be a lot of work and I don't care for vods.
